### ISSUE TITLE
transaction is not working

### ISSUE THREAD

**Issue by jianxuanbing** [odavid/typeorm-transactional-cls-hooked#3] opened 2018-10-30 15:35 UTC
The first save is success. the second save is no working. But I mock try throw exception. The create method  should not working. Now the first save is success.
```typescript
     @Transactional()
     public async create(entity: T): Promise<T> {
        await this.save(this.toEntity(entity), 'add');
        throw new Warning('测试事务操作');
        entity.id+='6666';
        return await this.save(this.toEntity(entity), 'add');
    }
```

```typescript
protected async save(entity: T, method: string): Promise<T> {
        if (!entity || typeof entity !== 'object') {
            throw new Warning('不是有效对象');
        }
        try {
            if (method === 'add') {
                entity = this.initCreationAudited(entity);
            }
            entity = this.initModificationAudited(entity);
            return await this.repository.save(entity as any);
        } catch (err) {
            throw new Warning(err.message);
        }
    }
```

**Comment by odavid** [comment] 2018-11-02 09:56
Hi,
I've tried to reproduce this behavior without success.
Does your repository extends the `BaseRepository`?

```typescript
import { BaseRepository } from 'typeorm-transactional-cls-hooked';
@EntityRepository(MyEntity)
export class MyEntityRepository extends BaseRepository<MyEntity> {}
``` 

It is important to use the BaseRepository, otherwise the transaction cannot work.

**Comment by jianxuanbing** [comment] 2018-11-05 09:19
Yes. I create the `RepositoryBase<Entity>` extends `BaseRepository<Entity>`. Then I created the `MyEntityRepository` extends before created `RepositoryBase<MyEntity>`.
`repository.base.ts`
```
import { BaseRepository } from 'typeorm-transactional-cls-hooked';
@EntityRepository(MyEntity)
export class RepositoryBase<TEntity> extends BaseRepository<TEntity>{}
```
`my-entity.repository.ts`
```
import { RepositoryBase} from './repository.base';
@EntityRepository(MyEntity)
export class MyEntityRepository extends RepositoryBase<MyEntity>{}
```

**Comment by odavid** [comment] 2018-11-05 18:37
Hi,

Can it be that the `initCreationAudited` and `initModificationAudited` are also using the entityManager or repository in some way?

I really could not reproduce this issue. In all my local attempts to throw exception after the first save, a record is not being created.

**Comment by jianxuanbing** [comment] 2018-11-06 02:42
This is my init entity method
```
/**
     * 初始化创建操作审计
     * @param entity 实体
     */
    protected initCreationAudited(entity: T): T {
        if (this.instanceOfCreationAudited(entity)) {
            entity.creationTime = new Date();
            entity.creatorId = '测试-创建人';
        }
        return entity;
    }

    /**
     * 初始化修改操作审计
     * @param entity 实体
     */
    protected initModificationAudited(entity: T): T {
        if (this.instanceOfModificationAudited(entity)) {
            entity.lastModificationTime = new Date();
            entity.lastModifierId = '测试-更新人';
        }
        return entity;
    }

    /**
     * 是否实现创建操作审计
     * @param object 对象
     */
    protected instanceOfCreationAudited(object: any): object is ICreationAudited {
        return 'creationTime' in object;
    }

    /**
     * 是否实现修改操作审计
     * @param object 对象
     */
    protected instanceOfModificationAudited(object: any): object is IModificationAudited {
        return 'lastModificationTime' in object;
    }
```

**Comment by jianxuanbing** [comment] 2018-11-06 02:43
The entity should extends `ObjectLiteral`? My entity is not extends `ObjectLiteral`

**Comment by jianxuanbing** [comment] 2018-11-07 11:34
i used mariadb(mysql)

**Comment by odavid** [comment] 2018-11-13 06:16
Ok, thank you for clarifying it.
Will close this issue. Feel free to re open if needed

**Closed by odavid** 2018-11-13 06:16 UTC
